/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.view;

import core.app.INavigator;
import core.controllers.IAppointmentController;
import core.controllers.IDoctorController;
import core.controllers.IHospitalizationController;
import core.controllers.IPatientController;
import core.controllers.IPrescription;
import core.controllers.PatientController;
import core.controllers.utils.Response;
import core.controllers.utils.Status;
import core.model.Doctor;
import core.model.IDataObserver;
import core.model.User;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class DoctorView extends javax.swing.JFrame implements IDataObserver {

    private int x, y;
    private long userId;
    private INavigator navigator;
    private IDoctorController doctorController;
    private IPatientController patientController;
    private IAppointmentController appointmentController;
    private IHospitalizationController hospitalizationController;
    private IPrescription prescriptionController;

    public DoctorView(long userId,
            IPatientController patientController,
            IDoctorController doctorController,
            IAppointmentController appointmentController,
            IHospitalizationController hospitalizationController,
            IPrescription prescriptionController,
            INavigator navigator) {
        initComponents();
        this.userId = userId;
        this.patientController = patientController;
        this.doctorController = doctorController;
        this.appointmentController = appointmentController;
        this.hospitalizationController = hospitalizationController;
        this.prescriptionController = prescriptionController;
        this.navigator = navigator;

        btnBackDV.setVisible(navigator.isAdminMode());

        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        btnRadioTotalAppointDVActionPerformed(null);

        Response res = patientController.getAllPatients();
        ArrayList<HashMap<String, Object>> patients = (ArrayList<HashMap<String, Object>>) res.getData().get("patients");
        inputSelectPatientDV.removeAllItems();
        inputSelectPatientDV.addItem("Select one");
        inputSelectPatientIDDV.removeAllItems();
        inputSelectPatientIDDV.addItem("Select one");
        for (HashMap<String, Object> pat : patients) {
            String fullname = String.valueOf(pat.get("fullname"));
            inputSelectPatientDV.addItem(fullname);
            inputSelectPatientIDDV.addItem(String.valueOf(pat.get("id")));
        }

        Response res2 = appointmentController.getDoctorAppointments(userId);
        ArrayList<HashMap<String, Object>> appointments = (ArrayList<HashMap<String, Object>>) res2.getData().get("appointments");

        inputSelectAppointIDDV.removeAllItems();
        inputSelectAppointDV.removeAllItems();
        inputCompleteAppointDV.removeAllItems();
        for (HashMap<String, Object> appt : appointments) {
            inputSelectAppointIDDV.addItem(String.valueOf(appt.get("id")));
            inputSelectAppointDV.addItem(String.valueOf(appt.get("id")));
            inputCompleteAppointDV.addItem(String.valueOf(appt.get("id")));
        }

        inputSelectAppointPresMediDV.removeAllItems();
        inputSelectAppointPresMediDV.addItem("Select one");
        for (HashMap<String, Object> appt : appointments) {
            inputSelectAppointPresMediDV.addItem(String.valueOf(appt.get("id")));
        }

        Response resHosp = hospitalizationController.getDoctorHospitalizations(userId);
        if (resHosp.getStatus() == Status.OK) {
            ArrayList<HashMap<String, Object>> hospis = (ArrayList<HashMap<String, Object>>) resHosp.getData().get("hospitalizations");
            inputSelectRequestDV.removeAllItems();
            inputSelectRequestDV.addItem("Select one");
            for (HashMap<String, Object> h : hospis) {
                inputSelectRequestDV.addItem(String.valueOf(h.get("id")));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new core.view.PanelRound();
        panelRound2 = new core.view.PanelRound();
        btnExitDV = new javax.swing.JButton();
        labelDV = new javax.swing.JLabel();
        btnBackDV = new javax.swing.JButton();
        tabbedPanelDV = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnRadioTotalAppointDV = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAppointmentsDV = new javax.swing.JTable();
        btnRadioPendingAppointDV = new javax.swing.JRadioButton();
        btnLogoutDV = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        inputSelectPatientDV = new javax.swing.JComboBox<>();
        labelPatientDV = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableHistoryPatientDV = new javax.swing.JTable();
        btnSearchHistoryPatientDV = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelFirstnameDV = new javax.swing.JLabel();
        inputFirstnameDV = new javax.swing.JTextField();
        labelLastnameDV = new javax.swing.JLabel();
        inputLastnameDV = new javax.swing.JTextField();
        labelSpecialtyDV = new javax.swing.JLabel();
        labelLicenseDV = new javax.swing.JLabel();
        inputLicenseDV = new javax.swing.JTextField();
        labelAssignedOfficeDV = new javax.swing.JLabel();
        inputUserDV = new javax.swing.JTextField();
        labelUserDV = new javax.swing.JLabel();
        inputAssignedOfficeDV = new javax.swing.JTextField();
        inputPassDV = new javax.swing.JTextField();
        labelPassDV = new javax.swing.JLabel();
        labelPassConfirDV = new javax.swing.JLabel();
        inputPassConfirDV = new javax.swing.JTextField();
        inputSpecialtyDV = new javax.swing.JComboBox<>();
        btnSavedModifyDV = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelAppointIDDV = new javax.swing.JLabel();
        labelAcceptMedAppointDV = new javax.swing.JLabel();
        inputSelectAppointIDDV = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnAppointIDDV = new javax.swing.JButton();
        labelRescMedAppointDV = new javax.swing.JLabel();
        labelAppointDV = new javax.swing.JLabel();
        inputSelectAppointDV = new javax.swing.JComboBox<>();
        btnAcceptResMediAppointDV = new javax.swing.JButton();
        labelNewTimeAppointDV = new javax.swing.JLabel();
        inputNewTimeAppointDV = new javax.swing.JTextField();
        labelReasonAppointDV = new javax.swing.JLabel();
        inputReasonAppointDV = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        labelCompleteMedAppointDV = new javax.swing.JLabel();
        labelAppoinDV = new javax.swing.JLabel();
        inputCompleteAppointDV = new javax.swing.JComboBox<>();
        labelDiagnosisDV = new javax.swing.JLabel();
        labelObservDV = new javax.swing.JLabel();
        labelRecoTreatDV = new javax.swing.JLabel();
        inputFollowIndicatDV = new javax.swing.JLabel();
        btnCompletDV = new javax.swing.JButton();
        labelHospiDV = new javax.swing.JLabel();
        labelReasHospiDV = new javax.swing.JLabel();
        labelDateEntryDV = new javax.swing.JLabel();
        inputDateEntryDV = new javax.swing.JTextField();
        labelEstimDuratDV = new javax.swing.JLabel();
        inputEstiDuratDV = new javax.swing.JTextField();
        labelHospiObservDV = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputHospiObservDV = new javax.swing.JTextArea();
        btnGenerateHospiDV = new javax.swing.JButton();
        inputSelectRequestDV = new javax.swing.JComboBox<>();
        btnRadioRequestDV = new javax.swing.JRadioButton();
        btnRadioPatientIDDV = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        inputTextAreaDiagnosisDV = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        inputTextAreaObservDV = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        inputTextAreaRecoTreatDV = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        inputTextAreaFollowIndicDV = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        btnCancelHospiDV = new javax.swing.JButton();
        inputSelectPatientIDDV = new javax.swing.JComboBox<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        inputTextAreaReasHospiDV = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        labelAppointPresMediDV = new javax.swing.JLabel();
        labelMediNamePresMediDV = new javax.swing.JLabel();
        inputMediNamePresMediDV = new javax.swing.JTextField();
        labelDosePresMediDV = new javax.swing.JLabel();
        inputDosePresMediDV = new javax.swing.JTextField();
        labelAdminRoutePresMediDV = new javax.swing.JLabel();
        inputAdminRoutePresMediDV = new javax.swing.JTextField();
        labelFrecuenPresMediDV = new javax.swing.JLabel();
        inputFrecuenPresMediDV = new javax.swing.JTextField();
        labelTretDuratPresMediDV = new javax.swing.JLabel();
        inputTreatDuratPresMediDV = new javax.swing.JTextField();
        labelAdditionInstrucPresMediDV = new javax.swing.JLabel();
        inputAdditInstrucPresMediDV = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePresMediDV = new javax.swing.JTable();
        btnAddPresMediDV = new javax.swing.JButton();
        btnPrescribePresMediDV = new javax.swing.JButton();
        inputSelectAppointPresMediDV = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setRadius(50);

        panelRound2.setRadius(50);
        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        btnExitDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnExitDV.setText("X");
        btnExitDV.setBorderPainted(false);
        btnExitDV.setContentAreaFilled(false);
        btnExitDV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExitDV.setFocusable(false);
        btnExitDV.setRequestFocusEnabled(false);
        btnExitDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitDVActionPerformed(evt);
            }
        });

        labelDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        labelDV.setText("DOCTOR VIEW");

        btnBackDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnBackDV.setText("Back");
        btnBackDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDV)
                .addGap(32, 32, 32)
                .addComponent(btnBackDV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExitDV)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnExitDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBackDV))
        );

        btnRadioTotalAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRadioTotalAppointDV.setText("Total appointments");
        btnRadioTotalAppointDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioTotalAppointDVActionPerformed(evt);
            }
        });

        tableAppointmentsDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Patient", "Specialty", "Type", "Status"
            }
        ));
        jScrollPane3.setViewportView(tableAppointmentsDV);

        btnRadioPendingAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRadioPendingAppointDV.setText("Pending appointments");
        btnRadioPendingAppointDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioPendingAppointDVActionPerformed(evt);
            }
        });

        btnLogoutDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogoutDV.setText("Logout");
        btnLogoutDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogoutDV)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(btnRadioTotalAppointDV)
                            .addGap(18, 18, 18)
                            .addComponent(btnRadioPendingAppointDV))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadioTotalAppointDV)
                    .addComponent(btnRadioPendingAppointDV))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnLogoutDV)
                .addGap(23, 23, 23))
        );

        tabbedPanelDV.addTab("Appointments visualization", jPanel4);

        inputSelectPatientDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputSelectPatientDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        labelPatientDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelPatientDV.setText("Patient");

        tableHistoryPatientDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableHistoryPatientDV);

        btnSearchHistoryPatientDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSearchHistoryPatientDV.setText("Search");
        btnSearchHistoryPatientDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHistoryPatientDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(labelPatientDV)
                        .addGap(18, 18, 18)
                        .addComponent(inputSelectPatientDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSearchHistoryPatientDV)
                .addGap(601, 601, 601))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPatientDV)
                    .addComponent(inputSelectPatientDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnSearchHistoryPatientDV)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        tabbedPanelDV.addTab("History Appointments of a patient", jPanel5);

        labelFirstnameDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelFirstnameDV.setText("Firstname");

        inputFirstnameDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelLastnameDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelLastnameDV.setText("Lastname");

        inputLastnameDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelSpecialtyDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelSpecialtyDV.setText("Specialty");

        labelLicenseDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelLicenseDV.setText("License Number");

        inputLicenseDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelAssignedOfficeDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelAssignedOfficeDV.setText("Assigned office");

        inputUserDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelUserDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelUserDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserDV.setText("User");

        inputAssignedOfficeDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        inputPassDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelPassDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelPassDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPassDV.setText("Password");

        labelPassConfirDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelPassConfirDV.setText("Password confirmation");

        inputPassConfirDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        inputSpecialtyDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputSpecialtyDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        btnSavedModifyDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSavedModifyDV.setText("Save");
        btnSavedModifyDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavedModifyDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(labelFirstnameDV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputFirstnameDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelLastnameDV)
                        .addGap(18, 18, 18)
                        .addComponent(inputLastnameDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelSpecialtyDV)
                        .addGap(18, 18, 18)
                        .addComponent(inputSpecialtyDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(labelLicenseDV)
                        .addGap(18, 18, 18)
                        .addComponent(inputLicenseDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAssignedOfficeDV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputAssignedOfficeDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPassDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inputUserDV, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(labelUserDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPassDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(labelPassConfirDV))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(btnSavedModifyDV))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(inputPassConfirDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstnameDV)
                    .addComponent(inputFirstnameDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLastnameDV)
                    .addComponent(inputLastnameDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpecialtyDV)
                    .addComponent(inputSpecialtyDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLicenseDV)
                    .addComponent(inputLicenseDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAssignedOfficeDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAssignedOfficeDV))
                .addGap(30, 30, 30)
                .addComponent(labelUserDV)
                .addGap(18, 18, 18)
                .addComponent(inputUserDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPassDV)
                .addGap(27, 27, 27)
                .addComponent(inputPassDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPassConfirDV)
                .addGap(18, 18, 18)
                .addComponent(inputPassConfirDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSavedModifyDV)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        tabbedPanelDV.addTab("Modify info", jPanel3);

        labelAppointIDDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelAppointIDDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAppointIDDV.setText("Appointment ID");

        labelAcceptMedAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelAcceptMedAppointDV.setText("Accept medical appointment");

        inputSelectAppointIDDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputSelectAppointIDDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAppointIDDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAppointIDDV.setText("Accept");
        btnAppointIDDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointIDDVActionPerformed(evt);
            }
        });

        labelRescMedAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelRescMedAppointDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRescMedAppointDV.setText("Reschedule medical appointment");

        labelAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelAppointDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAppointDV.setText("Appointment");

        inputSelectAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputSelectAppointDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        btnAcceptResMediAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAcceptResMediAppointDV.setText("Accept");
        btnAcceptResMediAppointDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptResMediAppointDVActionPerformed(evt);
            }
        });

        labelNewTimeAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelNewTimeAppointDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNewTimeAppointDV.setText("New time appointment");

        inputNewTimeAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelReasonAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelReasonAppointDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReasonAppointDV.setText("Reason for appointment");

        inputReasonAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labelCompleteMedAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelCompleteMedAppointDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompleteMedAppointDV.setText("Complete medical appointment");

        labelAppoinDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelAppoinDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAppoinDV.setText("Appointment");

        inputCompleteAppointDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputCompleteAppointDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        labelDiagnosisDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelDiagnosisDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDiagnosisDV.setText("Diagnosis");

        labelObservDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelObservDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelObservDV.setText("Observations");

        labelRecoTreatDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelRecoTreatDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRecoTreatDV.setText("Recommended treatment");

        inputFollowIndicatDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputFollowIndicatDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputFollowIndicatDV.setText("Follow-up indication");

        btnCompletDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCompletDV.setText("Complete");
        btnCompletDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletDVActionPerformed(evt);
            }
        });

        labelHospiDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelHospiDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHospiDV.setText("Hospitalization");

        labelReasHospiDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelReasHospiDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReasHospiDV.setText("Reason for hospitalization");

        labelDateEntryDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelDateEntryDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDateEntryDV.setText("Date of entry");

        inputDateEntryDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelEstimDuratDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelEstimDuratDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEstimDuratDV.setText("Estimated duration");

        inputEstiDuratDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelHospiObservDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelHospiObservDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHospiObservDV.setText("Observations");

        inputHospiObservDV.setColumns(20);
        inputHospiObservDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputHospiObservDV.setRows(5);
        jScrollPane1.setViewportView(inputHospiObservDV);

        btnGenerateHospiDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnGenerateHospiDV.setText("Generate");
        btnGenerateHospiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateHospiDVActionPerformed(evt);
            }
        });

        inputSelectRequestDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputSelectRequestDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        btnRadioRequestDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRadioRequestDV.setText("Requests");

        btnRadioPatientIDDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRadioPatientIDDV.setText("Patient ID");

        inputTextAreaDiagnosisDV.setColumns(20);
        inputTextAreaDiagnosisDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputTextAreaDiagnosisDV.setRows(5);
        jScrollPane6.setViewportView(inputTextAreaDiagnosisDV);

        inputTextAreaObservDV.setColumns(20);
        inputTextAreaObservDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputTextAreaObservDV.setRows(5);
        jScrollPane7.setViewportView(inputTextAreaObservDV);

        inputTextAreaRecoTreatDV.setColumns(20);
        inputTextAreaRecoTreatDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputTextAreaRecoTreatDV.setRows(5);
        jScrollPane8.setViewportView(inputTextAreaRecoTreatDV);

        inputTextAreaFollowIndicDV.setColumns(20);
        inputTextAreaFollowIndicDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputTextAreaFollowIndicDV.setRows(5);
        jScrollPane9.setViewportView(inputTextAreaFollowIndicDV);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCancelHospiDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCancelHospiDV.setText("Cancel");
        btnCancelHospiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelHospiDVActionPerformed(evt);
            }
        });

        inputSelectPatientIDDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputSelectPatientIDDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        inputTextAreaReasHospiDV.setColumns(20);
        inputTextAreaReasHospiDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputTextAreaReasHospiDV.setRows(5);
        jScrollPane10.setViewportView(inputTextAreaReasHospiDV);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAppointIDDV)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(inputSelectAppointIDDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67))))
                            .addComponent(labelAppointIDDV, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelAcceptMedAppointDV)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRescMedAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelAppointDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNewTimeAppointDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelReasonAppointDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(inputSelectAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(inputNewTimeAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(inputReasonAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(btnAcceptResMediAppointDV)))
                            .addGap(91, 91, 91))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnCompletDV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelAppoinDV, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelCompleteMedAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(inputCompleteAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDiagnosisDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelObservDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputFollowIndicatDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelRecoTreatDV, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelHospiDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDateEntryDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelEstimDuratDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelHospiObservDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputDateEntryDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputEstiDuratDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancelHospiDV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGenerateHospiDV))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(inputSelectRequestDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnRadioRequestDV)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRadioPatientIDDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(inputSelectPatientIDDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelReasHospiDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelCompleteMedAppointDV)
                        .addGap(10, 10, 10)
                        .addComponent(labelAppoinDV)
                        .addGap(18, 18, 18)
                        .addComponent(inputCompleteAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelDiagnosisDV)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelObservDV)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRecoTreatDV)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputFollowIndicatDV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCompletDV)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(labelAcceptMedAppointDV)
                                .addGap(18, 18, 18)
                                .addComponent(labelAppointIDDV)
                                .addGap(18, 18, 18)
                                .addComponent(inputSelectAppointIDDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnAppointIDDV))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(labelRescMedAppointDV)
                                .addGap(18, 18, 18)
                                .addComponent(labelAppointDV)
                                .addGap(18, 18, 18)
                                .addComponent(inputSelectAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelNewTimeAppointDV)
                                .addGap(18, 18, 18)
                                .addComponent(inputNewTimeAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelReasonAppointDV)
                                .addGap(18, 18, 18)
                                .addComponent(inputReasonAppointDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnAcceptResMediAppointDV)))
                        .addGap(18, 18, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelHospiDV)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadioRequestDV)
                    .addComponent(btnRadioPatientIDDV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSelectRequestDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSelectPatientIDDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelReasHospiDV)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDateEntryDV)
                .addGap(18, 18, 18)
                .addComponent(inputDateEntryDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelEstimDuratDV)
                .addGap(18, 18, 18)
                .addComponent(inputEstiDuratDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelHospiObservDV)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateHospiDV)
                    .addComponent(btnCancelHospiDV))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tabbedPanelDV.addTab("Request/Appointments", jPanel1);

        labelAppointPresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelAppointPresMediDV.setText("Appointment ID");

        labelMediNamePresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelMediNamePresMediDV.setText("Medication name");

        inputMediNamePresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelDosePresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelDosePresMediDV.setText("Dose");

        inputDosePresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelAdminRoutePresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelAdminRoutePresMediDV.setText("Administration route");

        inputAdminRoutePresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelFrecuenPresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelFrecuenPresMediDV.setText("Frecuency");

        inputFrecuenPresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelTretDuratPresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelTretDuratPresMediDV.setText("Treatment duration");

        inputTreatDuratPresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        labelAdditionInstrucPresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        labelAdditionInstrucPresMediDV.setText("Additional instructions");

        inputAdditInstrucPresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        tablePresMediDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Medication name", "Dose", "Administration route", "Treatment duration", "Additional instructions", "Frecuency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePresMediDV);

        btnAddPresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAddPresMediDV.setText("Add");
        btnAddPresMediDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPresMediDVActionPerformed(evt);
            }
        });

        btnPrescribePresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnPrescribePresMediDV.setText("Prescribe");
        btnPrescribePresMediDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescribePresMediDVActionPerformed(evt);
            }
        });

        inputSelectAppointPresMediDV.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        inputSelectAppointPresMediDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(labelAppointPresMediDV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputSelectAppointPresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(labelMediNamePresMediDV))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(labelTretDuratPresMediDV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputTreatDuratPresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(labelAdditionInstrucPresMediDV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputAdditInstrucPresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelFrecuenPresMediDV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputFrecuenPresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(inputMediNamePresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelDosePresMediDV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputDosePresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelAdminRoutePresMediDV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputAdminRoutePresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddPresMediDV))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(btnPrescribePresMediDV)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAppointPresMediDV)
                    .addComponent(labelMediNamePresMediDV)
                    .addComponent(inputMediNamePresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDosePresMediDV)
                    .addComponent(inputDosePresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAdminRoutePresMediDV)
                    .addComponent(inputAdminRoutePresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPresMediDV)
                    .addComponent(inputSelectAppointPresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTretDuratPresMediDV)
                    .addComponent(inputTreatDuratPresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAdditionInstrucPresMediDV)
                    .addComponent(inputAdditInstrucPresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFrecuenPresMediDV)
                    .addComponent(inputFrecuenPresMediDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnPrescribePresMediDV)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tabbedPanelDV.addTab("Prescribe medications", jPanel2);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPanelDV))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanelDV))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void btnExitDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitDVActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitDVActionPerformed

    private void btnRadioPendingAppointDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioPendingAppointDVActionPerformed
        btnRadioTotalAppointDV.setSelected(false);
        btnRadioPendingAppointDV.setSelected(true);
        DefaultTableModel model = (DefaultTableModel) tableAppointmentsDV.getModel();
        model.setRowCount(0);

        Response res = appointmentController.getDoctorPending(userId);
        ArrayList<HashMap<String, Object>> appointments = (ArrayList<HashMap<String, Object>>) res.getData().get("appointments");

        for (HashMap<String, Object> app : appointments) {
            model.addRow(new Object[]{
                app.get("id"),
                app.get("date") + " " + app.get("time"),
                app.get("patient"),
                app.get("specialty"),
                app.get("type"),
                app.get("status")
            });
        }
    }//GEN-LAST:event_btnRadioPendingAppointDVActionPerformed

    private void btnSavedModifyDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavedModifyDVActionPerformed
        String firstname = inputFirstnameDV.getText();
        String lastname = inputLastnameDV.getText();
        String specialty = inputSpecialtyDV.getItemAt(inputSpecialtyDV.getSelectedIndex());
        String licenseNumber = inputLicenseDV.getText();
        String assignedOffice = inputAssignedOfficeDV.getText();
        String username = inputUserDV.getText();
        String password = inputPassDV.getText();
        String comPassword = inputPassConfirDV.getText();
        Response res = doctorController.update(userId, username, firstname, lastname, password, comPassword, specialty, licenseNumber, assignedOffice);
        if (res.getStatus() == Status.OK) {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Update successful", JOptionPane.INFORMATION_MESSAGE);
            inputFirstnameDV.setText(""); inputLastnameDV.setText(""); inputLicenseDV.setText("");
            inputAssignedOfficeDV.setText(""); inputUserDV.setText(""); inputPassDV.setText("");
            inputPassConfirDV.setText(""); inputSpecialtyDV.setSelectedIndex(0);
        } else {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Oops..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSavedModifyDVActionPerformed

    private void btnLogoutDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutDVActionPerformed
        navigator.logout();
    }//GEN-LAST:event_btnLogoutDVActionPerformed

    private void btnBackDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDVActionPerformed
        navigator.showAdminView();
    }//GEN-LAST:event_btnBackDVActionPerformed

    private void btnCancelHospiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelHospiDVActionPerformed
//        if (btnRadioRequestDV.isSelected()) {
//            for(Hospitalization hosp : this.hospitalizations){
//                if (inputSelectRequestDV.getItemAt(inputSelectRequestDV.getSelectedIndex()) == hosp.getId()) {
//                    hosp.setStatus(HospitalizationStatus.CANCELED);
//                }
//            }
//        }
        if (!btnRadioRequestDV.isSelected()) {
            return;
        }

        String hospId = inputSelectRequestDV.getItemAt(inputSelectRequestDV.getSelectedIndex());
        if (hospId == null || hospId.equals("Select one")) {
            JOptionPane.showInternalMessageDialog(null, "Please select a hospitalization.", "Oops..", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Response res = hospitalizationController.rejectHospitalization(hospId, userId);
        if (res.getStatus() == Status.OK) {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Success", JOptionPane.INFORMATION_MESSAGE);
            inputSelectRequestDV.setSelectedIndex(0);
        } else {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Oops..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelHospiDVActionPerformed

    private void btnGenerateHospiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateHospiDVActionPerformed
//        if (btnRadioPatientIDDV.isSelected()) {
//            for(User user: this.users){
//                if (user instanceof Patient) {
//                    if (inputSelectPatientIDDV.getItemAt(inputSelectPatientIDDV.getSelectedIndex()).equals(user.getId())) {
//                        if (this.user instanceof Administrator) {
//                            String reason = inputTextAreaReasHospiDV.getText();
//                            String observations = inputHospiObservDV.getText();
//                            String entDate = inputDateEntryDV.getText();
//                            LocalDate entryDate = LocalDate.of(Integer.parseInt(entDate.substring(0, 4)), Integer.parseInt(entDate.substring(5, 7)), Integer.parseInt(entDate.substring(8)));
//                            this.hospitalizations.add(new Hospitalization("asdfasdf", (Patient)user, this.doctor, LocalDate.MAX, reason, RoomType.IMC, observations, HospitalizationStatus.ONGOING));
//                        }
//                    }
//                }
//            }
//        }
        if (!btnRadioPatientIDDV.isSelected()) {
            return;
        }

        String patientIdStr = inputSelectPatientIDDV.getItemAt(inputSelectPatientIDDV.getSelectedIndex());
        if (patientIdStr == null || patientIdStr.equals("Select one")) {
            JOptionPane.showInternalMessageDialog(null, "Please select a patient.", "Oops..", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long patientId = Long.parseLong(patientIdStr);
        String reason = inputTextAreaReasHospiDV.getText();
        String date = inputDateEntryDV.getText();
        String observations = inputHospiObservDV.getText();

        Response docRes = doctorController.getDoctor(userId);
        String doctorName = "";
        if (docRes.getStatus() == Status.OK) {
            doctorName = docRes.getData().get("firstname") + " " + docRes.getData().get("lastname");
        }
        Response res = hospitalizationController.requestHospitalization(
                patientId, reason, doctorName, date, "IMC", observations);

        if (res.getStatus() == Status.CREATED) {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Success", JOptionPane.INFORMATION_MESSAGE);
            inputTextAreaReasHospiDV.setText("");
            inputDateEntryDV.setText("");
            inputHospiObservDV.setText("");
        } else {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Oops..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerateHospiDVActionPerformed

    private void btnSearchHistoryPatientDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHistoryPatientDVActionPerformed
        String fullname = inputSelectPatientDV.getItemAt(inputSelectPatientDV.getSelectedIndex());
        Response res = appointmentController.getPatientAppointments(fullname);
        ArrayList<HashMap<String, Object>> appoints = (ArrayList<HashMap<String, Object>>) res.getData().get("appointments");

        DefaultTableModel model = (DefaultTableModel) tableHistoryPatientDV.getModel();
        model.setRowCount(0);

        for (HashMap<String, Object> app : appoints) {
            model.addRow(
                    new Object[]{
                        app.get("id"),
                        app.get("date") + " " + app.get("time"),
                        app.get("doctor"),
                        app.get("specialty"),
                        app.get("type"),
                        app.get("status")
                    }
            );
        }
    }//GEN-LAST:event_btnSearchHistoryPatientDVActionPerformed

    private void btnRadioTotalAppointDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioTotalAppointDVActionPerformed
        btnRadioPendingAppointDV.setSelected(false);
        btnRadioTotalAppointDV.setSelected(true);
        DefaultTableModel model = (DefaultTableModel) tableAppointmentsDV.getModel();
        model.setRowCount(0);

        Response res = appointmentController.getDoctorAppointments(userId);
        ArrayList<HashMap<String, Object>> appointments = (ArrayList<HashMap<String, Object>>) res.getData().get("appointments");

        for (HashMap<String, Object> app : appointments) {
            model.addRow(
                    new Object[]{
                        app.get("id"),
                        app.get("date") + " " + app.get("time"),
                        app.get("patient"),
                        app.get("specialty"),
                        app.get("type"),
                        app.get("status")
                    }
            );
        }
    }//GEN-LAST:event_btnRadioTotalAppointDVActionPerformed

    private void btnAppointIDDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointIDDVActionPerformed
        String idAppointment = inputSelectAppointIDDV.getItemAt(inputSelectAppointIDDV.getSelectedIndex());
        Response res = appointmentController.acceptAppointment(idAppointment, userId);
        if (res.getStatus() == Status.OK) {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Appointment acception successful", JOptionPane.INFORMATION_MESSAGE);
            inputSelectAppointIDDV.setSelectedIndex(0);
        } else {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Oops..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAppointIDDVActionPerformed

    private void btnCompletDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletDVActionPerformed
        String idAppointment = inputCompleteAppointDV.getItemAt(inputCompleteAppointDV.getSelectedIndex());
        String diagnosis = inputTextAreaDiagnosisDV.getText();
        String observations = inputTextAreaObservDV.getText();
        String recommendedTrea = inputTextAreaRecoTreatDV.getText();
        String followUp = inputTextAreaFollowIndicDV.getText();
        Response res = appointmentController.completeAppointment(idAppointment, userId, diagnosis, followUp, recommendedTrea, observations);
        if (res.getStatus() == Status.OK) {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Appointment completion successful", JOptionPane.INFORMATION_MESSAGE);
            inputCompleteAppointDV.setSelectedIndex(0);
            inputTextAreaDiagnosisDV.setText(""); inputTextAreaObservDV.setText("");
            inputTextAreaRecoTreatDV.setText(""); inputTextAreaFollowIndicDV.setText("");
        } else {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Oops..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCompletDVActionPerformed

    private void btnPrescribePresMediDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescribePresMediDVActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablePresMediDV.getModel();
        int rowCount = model.getRowCount();
        if (rowCount == 0) {
            JOptionPane.showInternalMessageDialog(null, "No medications to prescribe.", "Oops..", JOptionPane.ERROR_MESSAGE);
            return;
        }
        StringBuilder summary = new StringBuilder();
        int processedCount = 0;
        for (int row = 0; row < rowCount; row++) {
            String appointmentId = (String) model.getValueAt(row, 0);
            if (appointmentId == null || appointmentId.trim().isEmpty()) {
                continue;
            }
            processedCount++;
            String medicationName = (String) model.getValueAt(row, 1);
            String dose = (String) model.getValueAt(row, 2);
            String administrationRoute = (String) model.getValueAt(row, 3);
            String treatmentDuration = (String) model.getValueAt(row, 4);
            String additionalInstructions = (String) model.getValueAt(row, 5);
            String frequency = (String) model.getValueAt(row, 6);
            Response res = prescriptionController.prescribeMedication(
                    appointmentId, userId, medicationName, dose,
                    administrationRoute, treatmentDuration, additionalInstructions, frequency
            );
            if (res.getStatus() != Status.CREATED) {
                if (summary.length() > 0) {
                    summary.append("\n");
                }
                summary.append("- ").append(medicationName).append(": ").append(res.getMessage());
            }
        }
        model.setRowCount(0);
        inputMediNamePresMediDV.setText("");
        inputDosePresMediDV.setText("");
        inputAdminRoutePresMediDV.setText("");
        inputTreatDuratPresMediDV.setText("");
        inputAdditInstrucPresMediDV.setText("");
        inputFrecuenPresMediDV.setText("");
        if (processedCount == 0) {
            JOptionPane.showInternalMessageDialog(null, "No medications to prescribe.", "Oops..", JOptionPane.ERROR_MESSAGE);
        } else if (summary.length() == 0) {
            JOptionPane.showInternalMessageDialog(null, "All medications prescribed successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showInternalMessageDialog(null, "Some medications failed:\n" + summary.toString(), "Oops..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrescribePresMediDVActionPerformed

    private void btnAddPresMediDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPresMediDVActionPerformed
        // TODO add your handling code here:
//        DefaultTableModel model = (DefaultTableModel) tablePresMediDV.getModel();
//        
//        String appointmentId = inputSelectAppointPresMediDV.getItemAt(inputSelectAppointPresMediDV.getSelectedIndex());
//        String medicationName = inputMediNamePresMediDV.getText();
//        double dose = Double.parseDouble(inputDosePresMediDV.getText());
//        String administrationRoute = inputAdminRoutePresMediDV.getText();
//        int tratementduration = Integer.parseInt(inputTreatDuratPresMediDV.getText());
//        String aditionalIformation = inputAdditInstrucPresMediDV.getText();
//        int frecuency = Integer.parseInt(inputFrecuenPresMediDV.getText());
//        
//        model.addRow(new Object[]{appointmentId, medicationName, inputDosePresMediDV.getText(), administrationRoute, "" + tratementduration, aditionalIformation, "" + frecuency});
//        for(Appointment apo: this.appointments){
//            if (apo.getId().equals(appointmentId)){
//                apo.addPrescription(new Prescription(apo, medicationName, dose, administrationRoute, tratementduration, aditionalIformation, frecuency));
//            }
//        }
        DefaultTableModel model = (DefaultTableModel) tablePresMediDV.getModel();
        if (inputSelectAppointPresMediDV.getSelectedIndex() == 0) {
            JOptionPane.showInternalMessageDialog(null, "Please select an appointment.", "Oops..", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String appointmentId = inputSelectAppointPresMediDV.getItemAt(inputSelectAppointPresMediDV.getSelectedIndex());
        String medicationName = inputMediNamePresMediDV.getText();
        String doseText = inputDosePresMediDV.getText();
        String administrationRoute = inputAdminRoutePresMediDV.getText();
        String durationText = inputTreatDuratPresMediDV.getText();
        String instructions = inputAdditInstrucPresMediDV.getText();
        String frequencyText = inputFrecuenPresMediDV.getText();
        model.addRow(new Object[]{appointmentId, medicationName, doseText, administrationRoute, durationText, instructions, frequencyText});
    }//GEN-LAST:event_btnAddPresMediDVActionPerformed

    private void btnAcceptResMediAppointDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptResMediAppointDVActionPerformed
        String idAppointment = inputSelectAppointDV.getItemAt(inputSelectAppointDV.getSelectedIndex());
        String reasonChangeTime = inputReasonAppointDV.getText();
        String newTime = inputNewTimeAppointDV.getText();
        Response res = appointmentController.rescheduleAppointment(idAppointment, userId, newTime, reasonChangeTime);
        if (res.getStatus() == Status.OK) {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Appointment reschedule successful", JOptionPane.INFORMATION_MESSAGE);
            inputSelectAppointDV.setSelectedIndex(0);
            inputNewTimeAppointDV.setText(""); inputReasonAppointDV.setText("");
        } else {
            JOptionPane.showInternalMessageDialog(null, res.getMessage(), "Oops..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAcceptResMediAppointDVActionPerformed

    @Override
    public void onDataChanged(String storageName) {
        if ("AppointmentStorage".equals(storageName)) {
            if (btnRadioTotalAppointDV.isSelected()) {
                btnRadioTotalAppointDVActionPerformed(null);
            } else if (btnRadioPendingAppointDV.isSelected()) {
                btnRadioPendingAppointDVActionPerformed(null);
            }
        } else if ("HospitalizationStorage".equals(storageName)) {
            if (btnRadioTotalAppointDV.isSelected()) {
                btnRadioTotalAppointDVActionPerformed(null);
            } else if (btnRadioPendingAppointDV.isSelected()) {
                btnRadioPendingAppointDVActionPerformed(null);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptResMediAppointDV;
    private javax.swing.JButton btnAddPresMediDV;
    private javax.swing.JButton btnAppointIDDV;
    private javax.swing.JButton btnBackDV;
    private javax.swing.JButton btnCancelHospiDV;
    private javax.swing.JButton btnCompletDV;
    private javax.swing.JButton btnExitDV;
    private javax.swing.JButton btnGenerateHospiDV;
    private javax.swing.JButton btnLogoutDV;
    private javax.swing.JButton btnPrescribePresMediDV;
    private javax.swing.JRadioButton btnRadioPatientIDDV;
    private javax.swing.JRadioButton btnRadioPendingAppointDV;
    private javax.swing.JRadioButton btnRadioRequestDV;
    private javax.swing.JRadioButton btnRadioTotalAppointDV;
    private javax.swing.JButton btnSavedModifyDV;
    private javax.swing.JButton btnSearchHistoryPatientDV;
    private javax.swing.JTextField inputAdditInstrucPresMediDV;
    private javax.swing.JTextField inputAdminRoutePresMediDV;
    private javax.swing.JTextField inputAssignedOfficeDV;
    private javax.swing.JComboBox<String> inputCompleteAppointDV;
    private javax.swing.JTextField inputDateEntryDV;
    private javax.swing.JTextField inputDosePresMediDV;
    private javax.swing.JTextField inputEstiDuratDV;
    private javax.swing.JTextField inputFirstnameDV;
    private javax.swing.JLabel inputFollowIndicatDV;
    private javax.swing.JTextField inputFrecuenPresMediDV;
    private javax.swing.JTextArea inputHospiObservDV;
    private javax.swing.JTextField inputLastnameDV;
    private javax.swing.JTextField inputLicenseDV;
    private javax.swing.JTextField inputMediNamePresMediDV;
    private javax.swing.JTextField inputNewTimeAppointDV;
    private javax.swing.JTextField inputPassConfirDV;
    private javax.swing.JTextField inputPassDV;
    private javax.swing.JTextField inputReasonAppointDV;
    private javax.swing.JComboBox<String> inputSelectAppointDV;
    private javax.swing.JComboBox<String> inputSelectAppointIDDV;
    private javax.swing.JComboBox<String> inputSelectAppointPresMediDV;
    private javax.swing.JComboBox<String> inputSelectPatientDV;
    private javax.swing.JComboBox<String> inputSelectPatientIDDV;
    private javax.swing.JComboBox<String> inputSelectRequestDV;
    private javax.swing.JComboBox<String> inputSpecialtyDV;
    private javax.swing.JTextArea inputTextAreaDiagnosisDV;
    private javax.swing.JTextArea inputTextAreaFollowIndicDV;
    private javax.swing.JTextArea inputTextAreaObservDV;
    private javax.swing.JTextArea inputTextAreaReasHospiDV;
    private javax.swing.JTextArea inputTextAreaRecoTreatDV;
    private javax.swing.JTextField inputTreatDuratPresMediDV;
    private javax.swing.JTextField inputUserDV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelAcceptMedAppointDV;
    private javax.swing.JLabel labelAdditionInstrucPresMediDV;
    private javax.swing.JLabel labelAdminRoutePresMediDV;
    private javax.swing.JLabel labelAppoinDV;
    private javax.swing.JLabel labelAppointDV;
    private javax.swing.JLabel labelAppointIDDV;
    private javax.swing.JLabel labelAppointPresMediDV;
    private javax.swing.JLabel labelAssignedOfficeDV;
    private javax.swing.JLabel labelCompleteMedAppointDV;
    private javax.swing.JLabel labelDV;
    private javax.swing.JLabel labelDateEntryDV;
    private javax.swing.JLabel labelDiagnosisDV;
    private javax.swing.JLabel labelDosePresMediDV;
    private javax.swing.JLabel labelEstimDuratDV;
    private javax.swing.JLabel labelFirstnameDV;
    private javax.swing.JLabel labelFrecuenPresMediDV;
    private javax.swing.JLabel labelHospiDV;
    private javax.swing.JLabel labelHospiObservDV;
    private javax.swing.JLabel labelLastnameDV;
    private javax.swing.JLabel labelLicenseDV;
    private javax.swing.JLabel labelMediNamePresMediDV;
    private javax.swing.JLabel labelNewTimeAppointDV;
    private javax.swing.JLabel labelObservDV;
    private javax.swing.JLabel labelPassConfirDV;
    private javax.swing.JLabel labelPassDV;
    private javax.swing.JLabel labelPatientDV;
    private javax.swing.JLabel labelReasHospiDV;
    private javax.swing.JLabel labelReasonAppointDV;
    private javax.swing.JLabel labelRecoTreatDV;
    private javax.swing.JLabel labelRescMedAppointDV;
    private javax.swing.JLabel labelSpecialtyDV;
    private javax.swing.JLabel labelTretDuratPresMediDV;
    private javax.swing.JLabel labelUserDV;
    private core.view.PanelRound panelRound1;
    private core.view.PanelRound panelRound2;
    private javax.swing.JTabbedPane tabbedPanelDV;
    private javax.swing.JTable tableAppointmentsDV;
    private javax.swing.JTable tableHistoryPatientDV;
    private javax.swing.JTable tablePresMediDV;
    // End of variables declaration//GEN-END:variables
}
